Removed "ROLE_" to avoid the following error:
    java.lang.IllegalArgumentException: ROLE_ANONYMOUS should not start
    with ROLE_ since ROLE_ is automatically prepended when using
    hasRole. Consider using hasAuthority or access instead.

Also, added the corresponding test.